// Autogenerated from Pigeon (v26.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package io.github.fredapina.offline_navigation

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Travel mode for routing. */
enum class WireTravelMode(val raw: Int) {
  DRIVE(0),
  WALK(1),
  CYCLE(2);

  companion object {
    fun ofRaw(raw: Int): WireTravelMode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * A geographic point with an optional display name.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class WirePoint (
  val latitude: Double,
  val longitude: Double,
  val name: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WirePoint {
      val latitude = pigeonVar_list[0] as Double
      val longitude = pigeonVar_list[1] as Double
      val name = pigeonVar_list[2] as String?
      return WirePoint(latitude, longitude, name)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      latitude,
      longitude,
      name,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is WirePoint) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Result of a route build attempt.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class WireRouteBuildResult (
  val ok: Boolean,
  /** True when the build was aborted because the page is closing. */
  val cancelled: Boolean,
  /** Native routing result code; meaningful when [ok] is false. */
  val errorCode: Long,
  /** Country ids that must be downloaded before this route can be built. */
  val missingMaps: List<String>,
  val distanceText: String? = null,
  val distanceUnits: String? = null,
  val timeSeconds: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WireRouteBuildResult {
      val ok = pigeonVar_list[0] as Boolean
      val cancelled = pigeonVar_list[1] as Boolean
      val errorCode = pigeonVar_list[2] as Long
      val missingMaps = pigeonVar_list[3] as List<String>
      val distanceText = pigeonVar_list[4] as String?
      val distanceUnits = pigeonVar_list[5] as String?
      val timeSeconds = pigeonVar_list[6] as Long
      return WireRouteBuildResult(ok, cancelled, errorCode, missingMaps, distanceText, distanceUnits, timeSeconds)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      ok,
      cancelled,
      errorCode,
      missingMaps,
      distanceText,
      distanceUnits,
      timeSeconds,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is WireRouteBuildResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          WireTravelMode.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WirePoint.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WireRouteBuildResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is WireTravelMode -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is WirePoint -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is WireRouteBuildResult -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface OfflineNavApi {
  /** Initializes the native map engine; completes when the framework is ready. */
  fun initialize(callback: (Result<Unit>) -> Unit)
  fun isInitialized(): Boolean
  /** Bytes of base world maps still missing (0 = present). */
  fun getBaseMapBytes(): Long
  /**
   * Downloads missing base world maps; progress streams on the downloads
   * EventChannel under the `__base__` pseudo country id.
   */
  fun downloadBaseMaps(callback: (Result<Unit>) -> Unit)
  fun cancelBaseMapDownload()
  fun hasLocationPermission(): Boolean
  fun requestLocationPermission(callback: (Result<Boolean>) -> Unit)
  /**
   * The engine's bundled map-data version (e.g. "260111"). Downloads only
   * work while the CDN still serves this version.
   */
  fun getDataVersion(): String
  /** Country map id covering the point, or null (e.g. open sea). */
  fun resolveCountry(latitude: Double, longitude: Double): String?
  /** Native storage status code for the country (see MapStatus in models.dart). */
  fun getCountryStatus(countryId: String): Long
  fun startDownload(countryIds: List<String>)
  fun cancelDownload(countryIds: List<String>)
  fun buildRoute(start: WirePoint, destination: WirePoint, mode: WireTravelMode, callback: (Result<WireRouteBuildResult>) -> Unit)
  fun startGuidance(simulate: Boolean, voice: Boolean, callback: (Result<Unit>) -> Unit)
  fun stopGuidance()
  fun closeRouting()
  fun setViewport(latitude: Double, longitude: Double, zoom: Long)
  fun setKeepScreenOn(on: Boolean)

  companion object {
    /** The codec used by OfflineNavApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `OfflineNavApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: OfflineNavApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.offline_navigation.OfflineNavApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.initialize{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.offline_navigation.OfflineNavApi.isInitialized$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isInitialized())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.offline_navigation.OfflineNavApi.getBaseMapBytes$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getBaseMapBytes())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.offline_navigation.OfflineNavApi.downloadBaseMaps$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.downloadBaseMaps{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.offline_navigation.OfflineNavApi.cancelBaseMapDownload$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.cancelBaseMapDownload()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.offline_navigation.OfflineNavApi.hasLocationPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.hasLocationPermission())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.offline_navigation.OfflineNavApi.requestLocationPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.requestLocationPermission{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.offline_navigation.OfflineNavApi.getDataVersion$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getDataVersion())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.offline_navigation.OfflineNavApi.resolveCountry$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val latitudeArg = args[0] as Double
            val longitudeArg = args[1] as Double
            val wrapped: List<Any?> = try {
              listOf(api.resolveCountry(latitudeArg, longitudeArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.offline_navigation.OfflineNavApi.getCountryStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val countryIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.getCountryStatus(countryIdArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.offline_navigation.OfflineNavApi.startDownload$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val countryIdsArg = args[0] as List<String>
            val wrapped: List<Any?> = try {
              api.startDownload(countryIdsArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.offline_navigation.OfflineNavApi.cancelDownload$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val countryIdsArg = args[0] as List<String>
            val wrapped: List<Any?> = try {
              api.cancelDownload(countryIdsArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.offline_navigation.OfflineNavApi.buildRoute$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val startArg = args[0] as WirePoint
            val destinationArg = args[1] as WirePoint
            val modeArg = args[2] as WireTravelMode
            api.buildRoute(startArg, destinationArg, modeArg) { result: Result<WireRouteBuildResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.offline_navigation.OfflineNavApi.startGuidance$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val simulateArg = args[0] as Boolean
            val voiceArg = args[1] as Boolean
            api.startGuidance(simulateArg, voiceArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.offline_navigation.OfflineNavApi.stopGuidance$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopGuidance()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.offline_navigation.OfflineNavApi.closeRouting$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.closeRouting()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.offline_navigation.OfflineNavApi.setViewport$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val latitudeArg = args[0] as Double
            val longitudeArg = args[1] as Double
            val zoomArg = args[2] as Long
            val wrapped: List<Any?> = try {
              api.setViewport(latitudeArg, longitudeArg, zoomArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.offline_navigation.OfflineNavApi.setKeepScreenOn$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val onArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setKeepScreenOn(onArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
